import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc, getDocs, query, where, serverTimestamp } from 'firebase/firestore';
import { getAuth, signInWithPopup, GoogleAuthProvider } from 'firebase/auth';

const autoForgeConfig = {
  projectId: "ai-studio-applet-webapp-e4b87",
  appId: "1:1027839418693:web:333649f937a1782f7b1e2c",
  apiKey: "AIzaSyC4o4fk72EYl3jMH88uIV0hKhAfhdr5l7g",
  authDomain: "ai-studio-applet-webapp-e4b87.firebaseapp.com",
};

const app = initializeApp(autoForgeConfig, 'autoforge');
export const autoForgeDb = getFirestore(app, "ai-studio-345bf97c-82b3-4621-b2bb-753d89609895");
export const autoForgeAuth = getAuth(app);

export const signInToAutoForge = async () => {
  const provider = new GoogleAuthProvider();
  return signInWithPopup(autoForgeAuth, provider);
};

export const fetchProjects = async () => {
  console.log("Fetching AutoForge projects for user:", autoForgeAuth.currentUser?.uid);
  if (!autoForgeAuth.currentUser) {
    throw new Error('Not authenticated in AutoForge');
  }
  
  try {
    const q = query(
      collection(autoForgeDb, 'projects'),
      where('userId', '==', autoForgeAuth.currentUser.uid)
    );
    const snap = await getDocs(q);
    const projects = snap.docs.map(doc => ({ id: doc.id, ...doc.data() }));
    console.log("Found AutoForge projects:", projects.length);
    return projects;
  } catch (error: any) {
    console.error("Error fetching projects from AutoForge:", error);
    throw new Error("Firestore GetDocs Error: " + error.message);
  }
};

export const pushToAutoForgeTask = async (projectId: string, title: string, generatedPrompt: string) => {
  if (!autoForgeAuth.currentUser) {
    throw new Error('Not authenticated in AutoForge');
  }
  
  const payload = {
    projectId,
    userId: autoForgeAuth.currentUser.uid,
    title: title,
    description: "Generated by Pipeline",
    strategy: generatedPrompt,
    logs: [],
    generatedFiles: [],
    status: 'todo',
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  };
  
  console.log("Pushing Task to AutoForge:", payload);
  try {
    const docRef = await addDoc(collection(autoForgeDb, 'tasks'), payload);
    console.log("Successfully pushed task with ID:", docRef.id);
    return docRef;
  } catch (err: any) {
    console.error("Error pushing task to AutoForge:", err);
    throw new Error("Firestore AddDoc Error: " + err.message);
  }
};
