import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc, getDocs, query, where, serverTimestamp } from 'firebase/firestore';
import { getAuth, signInWithPopup, GoogleAuthProvider } from 'firebase/auth';

const autoForgeConfig = {
  projectId: "ai-studio-applet-webapp-e4b87",
  appId: "1:1027839418693:web:333649f937a1782f7b1e2c",
  apiKey: "AIzaSyC4o4fk72EYl3jMH88uIV0hKhAfhdr5l7g",
  authDomain: "ai-studio-applet-webapp-e4b87.firebaseapp.com",
};

const app = initializeApp(autoForgeConfig, 'autoforge');
export const autoForgeDb = getFirestore(app, "ai-studio-345bf97c-82b3-4621-b2bb-753d89609895");
export const autoForgeAuth = getAuth(app);

export const signInToAutoForge = async () => {
  const provider = new GoogleAuthProvider();
  return signInWithPopup(autoForgeAuth, provider);
};

export const fetchProjects = async () => {
  if (!autoForgeAuth.currentUser) {
    throw new Error('Not authenticated in AutoForge');
  }
  const q = query(
    collection(autoForgeDb, 'projects'),
    where('userId', '==', autoForgeAuth.currentUser.uid)
  );
  const snap = await getDocs(q);
  return snap.docs.map(doc => ({ id: doc.id, ...doc.data() }));
};

export const pushToAutoForgeTask = async (projectId: string, title: string, generatedPrompt: string) => {
  if (!autoForgeAuth.currentUser) {
    throw new Error('Not authenticated in AutoForge');
  }
  
  const payload = {
    projectId,
    userId: autoForgeAuth.currentUser.uid,
    title: title,
    description: "Generated by Pipeline",
    strategy: generatedPrompt,
    status: 'todo',
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  };
  
  console.log("Pushing Task to AutoForge:", payload);
  await addDoc(collection(autoForgeDb, 'tasks'), payload);
};
